export enum EQuery {
  CONTAINERS = "containers",
  CONTAINER_DETAIL = "container-detail",
  IMAGES = "images",
  VOLUMES = "volumes",
  NETWORKS = "networks",
  COMPOSE_STACKS = "compose-stacks",
  COMPOSE_GRAPH = "compose-graph",
  METRICS = "metrics",
  LEARN_CONCEPTS = "learn-concepts",
  LEARN_CONCEPT = "learn-concept",
  LEARN_QUIZ = "learn-quiz",
  LEARN_CONTEXT = "learn-context",
  SWARM_INFO = "swarm-info",
  SWARM_NODES = "swarm-nodes",
  SWARM_SERVICES = "swarm-services",
  SWARM_SERVICE_DETAIL = "swarm-service-detail",
  SWARM_TASKS = "swarm-tasks",
  SWARM_STACKS = "swarm-stacks",
}
